### ISSUE TITLE
Connection Reset Error

### ISSUE THREAD

**Issue by jkalwar** [jenkinsci/rally-plugin#25]
We are getting the below error recently. I guess it might be a plugin issue , but wanted to know the exact reason for this issue. Is it an issue from the Rally side ?
Checking Exit code: 1
	rally update plug-in error: could not update changeset entry: java.net.SocketException: Connection reset
com.jenkins.plugins.rally.RallyException: java.net.SocketException: Connection reset
	at com.jenkins.plugins.rally.utils.RallyQueryBuilder.andExecuteReturningRef(RallyQueryBuilder.java:78)
	at com.jenkins.plugins.rally.connector.RallyConnector.queryForRepository(RallyConnector.java:127)
	at com.jenkins.plugins.rally.service.RallyService.updateChangeset(RallyService.java:43)
	at com.jenkins.plugins.rally.RallyPlugin.perform(RallyPlugin.java:109)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:533)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:401)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:120)
	at com.rallydev.rest.client.HttpClient.executeRequest(HttpClient.java:157)
	at com.rallydev.rest.client.HttpClient.doRequest(HttpClient.java:145)
	at com.rallydev.rest.client.ApiKeyClient.doRequest(ApiKeyClient.java:37)
	at com.rallydev.rest.client.HttpClient.doGet(HttpClient.java:221)
	at com.rallydev.rest.RallyRestApi.query(RallyRestApi.java:168)
	at com.jenkins.plugins.rally.utils.RallyQueryBuilder.andExecuteReturningRef(RallyQueryBuilder.java:70)
	... 12 more
	rally update plug-in error: could not update changeset entry: java.net.SocketException: Connection reset
com.jenkins.plugins.rally.RallyException: java.net.SocketException: Connection reset
	at com.jenkins.plugins.rally.utils.RallyQueryBuilder.andExecuteReturningRef(RallyQueryBuilder.java:78)
	at com.jenkins.plugins.rally.connector.RallyConnector.queryForRepository(RallyConnector.java:127)
	at com.jenkins.plugins.rally.service.RallyService.updateChangeset(RallyService.java:43)
	at com.jenkins.plugins.rally.RallyPlugin.perform(RallyPlugin.java:109)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:533)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:401)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:158)
	at org.apache.http.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:120)
	at com.rallydev.rest.client.HttpClient.executeRequest(HttpClient.java:157)
	at com.rallydev.rest.client.HttpClient.doRequest(HttpClient.java:145)
	at com.rallydev.rest.client.ApiKeyClient.doRequest(ApiKeyClient.java:37)
	at com.rallydev.rest.client.HttpClient.doGet(HttpClient.java:221)
	at com.rallydev.rest.RallyRestApi.query(RallyRestApi.java:168)

**Comment by jkalwar** [comment]
We just wanted to prevent the build failure due to this issue. Is there a way to prevent build failure due to Rally API issue ?

**Comment by mike-rogers** [comment]
Currently no, an issue with Rally API's availability will result in a build failure. I think the code change would be reasonably straightforward but I can't commit to it at the moment due to other obligations. ☹️
